#!/usr/bin/env bash
sshpass -p root ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@$1 "cd /tmp && wget http://$2:8080/firmware.bin -O firmware.bin"
sshpass -p root ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@$1 "cd /tmp && /sbin/mtd -r write firmware.bin firmware"
